#!/bin/bash
CURRDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd $CURRDIR
if [ ! -d classFiles ]; then
    mkdir classFiles
fi
javac -cp ".:dependencies/JSONparser/JSON-java.jar" -d classes/tfighter src/tfighter/*.java
java -cp ".:dependencies/JSONparser/JSON-java.jar" classes/tfighter/TextFighter
